/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mathe;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Rechteck r = new Rechteck(3,7);
        System.out.println(r + "Diagonale: " + r.getDiagonale());
        //noch eine nachträgliche Änderung
        //und noch eine
    }
}
